### ISSUE TITLE
Continuous Integration/Deployment

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/hrrr-smoke-vis#7]
Set up CI/CD with either GitHub Actions or some other CI service.

## Definition of Done

* [ ] The frontend is hosted somewhere
* [ ] Frontend tests are run automatically whenever changes to the frontend are pushed to a branch
* [ ] Frontend tests are run automatically whenever _any_ changes are pushed to the main branch
* [ ] Frontend is updated in production whenever changes to the frontend are pushed to the main branch

### Stretch Goals

* [ ] Review apps are created for any branch containing changes to the frontend

**Comment by esheehan-gsl** [comment]
There's a small chance that we'll end up hosting this on AWS. I'm waiting to get permissions added to my AWS account that would allow me to connect it to GitHub so AppRunner can deploy containers, and to get access to a document on the security scanning requirements for containers. If that works out, we can deploy to AppRunner, otherwise we'll end up hosting this in an on-prem VM, in which case CI/CD is going to be more complicated.

**Comment by esheehan-gsl** [comment]
@jqs-noaa Do you want to reuse the hostname for your original HRRR Smoke application: https://hwp-viz.gsd.esrl.noaa.gov/smoke/index.html#? Or should we pick a new hostname?

**Comment by jqs-noaa** [comment]
@esheehan-gsl  We should pick a new host name, since we are GSL now.
