### ISSUE TITLE
Show height in km for cross-section

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/hrrr-smoke-vis#78]
**Describe the change you'd like**
Include the height along with the isobaric pressure levels for the y-axis of the cross-section charts.

**Comment by jqs-noaa** [comment]
altitude in kilometers = Math.round((44330.7606715224)*(1-Math.pow(P/1013.25,1/5.2559))) where P is pressure in Millibars 

Pressure needs to be between 1070 and 44 mb for this to be valid.

we probably want some standard altitude levels like every 2K feet.  

going the other way:

Pressure MB = Math.round(100*1013.25*Math.pow((1-0.0000225577*H),5.2559))/100; where H is altitude in km

Assuming H is between 110000 and -500 km

**Comment by jqs-noaa** [comment]
Standard Sea Level Pressure in Millibars =  1013.25, the others I believe are coefficients
